# Generated by Django 6.1.1 on 2026-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "categorias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "clientes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Observacao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                ("data_registro", models.DateField(null=True)),
            ],
            options={
                "db_table": "observacoes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "perfis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("prioridade", models.CharField(max_length=20)),
                ("status", models.CharField(default="ABERTO", max_length=20)),
                ("data_abertura", models.DateField(null=True)),
            ],
            options={
                "db_table": "servicos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
    ]
